development:
  adapter: postgresql
  encoding: unicode
  database: api-demo_development
  pool: 5




test:
  adapter: postgresql
  encoding: unicode
  database: api-demo_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: api-demo_production
  pool: 5
